### ISSUE TITLE
Missing AndroidManifest.xm file

### ISSUE THREAD

**Issue by PrestanceDesign** [thheller/reagent-react-native#1]
Hi!

I have this error when launching `react-native run-android`.
Do I must fix manually ? Thx

```
Starting JS server...

ENOENT: no such file or directory, open 'app/src/main/AndroidManifest.xml'

Error: ENOENT: no such file or directory, open 'app/src/main/AndroidManifest.xml'
    at Object.openSync (fs.js:454:3)
    at Object.readFileSync (fs.js:354:35)
    at buildAndRun (/tmp/reagent-react-native/node_modules/react-native/local-cli/runAndroid/runAndroid.js:112:3)
    at /tmp/reagent-react-native/node_modules/react-native/local-cli/runAndroid/runAndroid.js:65:12
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by thheller** [comment]
I don't really know. Last time I ran this example it worked.

I suspect that something in `react-native` changed and the files it generated changed. Probably need to re-recreate a new project and run `react-native init` and then copy the CLJS related files there.

**Comment by PrestanceDesign** [comment]
I close this issue because it's a missing /android/app/ directory missing due to .gitignore config.
I have create the PR: https://github.com/thheller/reagent-react-native/pull/2
