### ISSUE TITLE
App not reloading on compilation. 

### ISSUE THREAD

**Issue by zendevil** [thheller/reagent-react-native#6]
I am shadow-watching the src, and when I change something in test/app.cljs the [:app] build compilation successfully happens, but the view on the phone/emulator doesn't change and remains the Welcome to React page.
Changing App.js directly works fine.

**Comment by thheller** [comment]
You shouldn't even be seeing the "Welcome to React page".

Make sure you change the `index.js` file `react-native` generated in the projec root. Should be like this

https://github.com/thheller/reagent-react-native/blob/master/react-native/index.js

**Comment by zendevil** [comment]
Thanks, that error is gone now. But there's another error:

```
Invariant Violation: "MyApp" has not been registered. This can happen if

* Metro (the local dev server) is run from the wrong folder. Check if Metro is running, stop it and restart it in the current project.
* A module failed to load due to an error and AppRegistry.registerComponent wasn't called.

```

**Comment by thheller** [comment]
See

https://github.com/thheller/reagent-react-native/blob/cbb2ea37a5487238bca10261474f0a59641add11/src/main/test/app.cljs#L59

Use `MyApp` instead as the name.
