### ISSUE TITLE
Unable to require re-frame in app.cljs

### ISSUE THREAD

**Issue by zendevil** [thheller/reagent-react-native#7]
Sorry, I don't know much about how re-frame works. I require re-frame for building an actual app like so in app.cljs:

```
[re-frame.core :as re-frame]
```

The [:app] build is successful but in the device I get:

```
addEventListener and attachEvent are unavailable.
```

**Comment by thheller** [comment]
Sorry but this is not the place to ask re-frame questions. I don't use neither re-frame nor react-native.
